name: Publish

on:
  release:
    types: [released,prereleased]

jobs:
  publish:
    name: Publish extension version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: .github/pipeline

      - uses: bahmutov/npm-install@v1

      - run: npm run build
        working-directory: .github/pipeline

      - name: Create deployment
        uses: actions/github-script@v3
        env:
          CHROME_LIVE: ${{ secrets.CHROME_LIVE }}
          CHROME_DEVELOPER: ${{ secrets.CHROME_DEVELOPER }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          FIREFOX_LIVE: ${{ secrets.FIREFOX_LIVE }}
          FIREFOX_DEVELOPER: ${{ secrets.FIREFOX_DEVELOPER }}
          FIREFOX_ISS: ${{ secrets.FIREFOX_ISS }}
          FIREFOX_SECRET: ${{ secrets.FIREFOX_SECRET }}
        with:
          working-directory: .
          script: |
            const owner = '${{ github.repository_owner }}';
            const repo = '${{ github.repository }}'.split('/')[1];
            const ref = '${{ github.ref }}';

            const [version] = ref.split('/').reverse();

            const action = '${{ github.event.action }}';

            const createDeployments = require(`${process.env.GITHUB_WORKSPACE}/.github/pipeline/build/publish.js`).default;

            await createDeployments(version, action, owner, repo, ref, github);
