name: Publish

on:
  release:
    types: [released,prereleased]

jobs:
  publish:
    name: Publish extension version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: .github/pipeline

      - uses: bahmutov/npm-install@v1

      - run: npm run build
        working-directory: .github/pipeline

      - name: Create deployment
        uses: actions/github-script@v3
        env:
          ASSET_PATH: dist
          CHROME_LIVE_ID: ${{ secrets.CHROME_LIVE_ID }}
          CHROME_DEVELOPER_ID: ${{ secrets.CHROME_DEVELOPER_ID }}
          CHROME_OAUTH_CLIENT_ID: ${{ secrets.CHROME_OAUTH_CLIENT_ID }}
          CHROME_OAUTH_CLIENT_SECRET: ${{ secrets.CHROME_OAUTH_CLIENT_SECRET }}
          CHROME_OAUTH_REFRESH_TOKEN: ${{ secrets.CHROME_OAUTH_REFRESH_TOKEN }}
          FIREFOX_LIVE_ID: ${{ secrets.FIREFOX_LIVE_ID }}
          FIREFOX_DEVELOPER_ID: ${{ secrets.FIREFOX_DEVELOPER_ID }}
          FIREFOX_JWT_ISS: ${{ secrets.FIREFOX_JWT_ISS }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
        with:
          script: |
            const owner = '${{ github.repository_owner }}';
            const repo = '${{ github.repository }}'.split('/')[1];
            const ref = '${{ github.ref }}';

            const [version] = ref.split('/').reverse();

            const action = '${{ github.event.action }}';

            const createDeployments = require(`${process.env.GITHUB_WORKSPACE}/.github/pipeline/build/publish.js`).default;

            await createDeployments(version, action, owner, repo, ref, github);
