name: Publish

on:
  release:
    types: [released,prereleased]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Releasing live"
        if: github.event.action == 'released'

      - run: |
          echo "Releasing preview"
        if: github.event.action == 'prereleased'

      - run: |
          echo "Always!"

