name: Publish

on:
  release:
    types: [released,prereleased]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - run: 'npm ci'
        working-directory: '.github/pipeline'

      - name: Create deployment
        uses: actions/github-script@v3
        with:
          script: |
            const owner = '${{ github.repository_owner }}';
            const repo = '${{ github.repository }}'.split('/')[1];
            const ref = '${{ github.ref }}';

            const [version] = ref.split('/').reverse();

            const action = '${{ github.event.action }}';

            const createDeployments = require(`${process.env.GITHUB_WORKSPACE}/.github/pipeline/build/functions/create-deployments/create-deployments.js`);

            await createDeployments(version, action, owner, repo, ref, github);
