name: Publish

on:
  release:
    types: [released,prereleased]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - run: |
          make publish channel=public
        if: github.event.action == 'released'

      - run: |
          make publish channel=preview
        if: github.event.action == 'prereleased'

      - name: Create deployment
        uses: actions/github-script@v3
        with:
          script: |
            const targets = ['Chrome', 'Firefox'];

            const owner = '${{ github.repository_owner }}';
            const repo = '${{ github.repository }}'.split('/')[1];
            const ref = '${{ github.ref }}';

            const environment = '${{ github.event.action }}' === 'released' ? 'Public' : 'Preview';

            await Promise.all(targets.map(async (target) => {
              const { data: { id } } = await github.repos.createDeployment({
                owner,
                repo,
                ref,
                required_contexts: [],
                environment: `${target} - ${environment}`
              });

              github.repos.createDeploymentStatus({
                owner,
                repo,
                deployment_id: id,
                state: 'pending'
              });
            }));
