name: Publish

on:
  release:
    types: [released,prereleased]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1

      - run: 'npm ci'
        working-directory: '.github/pipeline'

      - name: Create deployment
        uses: actions/github-script@v3
        with:
          script: |
            const targets = ['Chrome', 'Firefox'];

            const execa = require(`${process.env.GITHUB_WORKSPACE}/.github/pipeline/node_modules/execa`);

            const owner = '${{ github.repository_owner }}';
            const repo = '${{ github.repository }}'.split('/')[1];
            const ref = '${{ github.ref }}';

            const [version] = ref.split('/').reverse();

            const environment = {
              'released': 'Public',
              'prereleased': 'Preview'
            }['${{ github.event.action }}'];

            const channel = environment.toLowerCase();

            for(let target of targets) {
              const { data: { id } } = await github.repos.createDeployment({
                owner,
                repo,
                ref,
                required_contexts: [],
                environment: `${target} - ${environment}`
              });

              try {
                const { stdout } = await execa('make', ['publish', `target=${target.toLowerCase()}`, `channel=${channel}`]);

                console.log(stdout);
              } catch (error) {
                let description = `Failed to publish ${version}: ${error.message}`;

                if (description.length > 140)
                  description = `${description.slice(0, 136)}...`;

                github.repos.createDeploymentStatus({
                  owner,
                  repo,
                  deployment_id: id,
                  state: 'error',
                  description,
                  log_url: 'https://github.com/${{ github.repository }}/runs/${{ github.run_id }}'
                });

                continue;
              }

              github.repos.createDeploymentStatus({
                owner,
                repo,
                deployment_id: id,
                state: 'pending',
                description: `Version ${version} is in review`
              });
            }
