name: Update Deployment Status

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  prepare:
    name: Prepare pipeline scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ./.github/pipeline

      - run: npm run build
        working-directory: ./.github/pipeline

  status:
    name: Update Deployment Status
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v2

      - name: Update all deployments
        uses: actions/github-script@v3
        env:
          CHROME_PUBLIC: ${{ secrets.CHROME_PUBLIC }}
          CHROME_PREVIEW: ${{ secrets.CHROME_PREVIEW }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          FIREFOX_PUBLIC: ${{ secrets.FIREFOX_PUBLIC }}
        with:
          script: |
            const owner = '${{ github.repository_owner }}';
            const repo = '${{ github.repository }}'.split('/')[1];

            const updateDeploymentStatuses = require(`${process.env.GITHUB_WORKSPACE}/.github/pipeline/build/functions/update-deployment-statuses/update-deployment-statuses.js`);

            await updateDeploymentStatuses(owner, repo, github, core);
