name: Update Deployment Status

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  status:
    name: Update Deployment Status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ./.github/pipeline

      - run: npm run build
        working-directory: ./.github/pipeline

      - name: Update all deployments
        uses: actions/github-script@v3
        env:
          CHROME_LIVE_ID: ${{ secrets.CHROME_LIVE_ID }}
          CHROME_DEVELOPER_ID: ${{ secrets.CHROME_DEVELOPER_ID }}
          CHROME_OAUTH_CLIENT_ID: ${{ secrets.CHROME_OAUTH_CLIENT_ID }}
          CHROME_OAUTH_CLIENT_SECRET: ${{ secrets.CHROME_OAUTH_CLIENT_SECRET }}
          CHROME_OAUTH_REFRESH_TOKEN: ${{ secrets.CHROME_OAUTH_REFRESH_TOKEN }}
          FIREFOX_LIVE_ID: ${{ secrets.FIREFOX_LIVE_ID }}
          FIREFOX_DEVELOPER_ID: ${{ secrets.FIREFOX_DEVELOPER_ID }}
          FIREFOX_JWT_ISS: ${{ secrets.FIREFOX_JWT_ISS }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
        with:
          script: |
            const owner = '${{ github.repository_owner }}';
            const repo = '${{ github.repository }}'.split('/')[1];

            const updateDeploymentStatuses = require(`${process.env.GITHUB_WORKSPACE}/.github/pipeline/build/status.js`).default;

            await updateDeploymentStatuses(owner, repo, github);
