name: Update Deployment Status

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  status:
    name: Update Deployment Status
    runs-on: ubuntu-latest
    steps:
      - name: Update all deployments
        uses: actions/github-script@v3
        with:
          script: |
            const owner = '${{ github.repository_owner }}';
            const repo = '${{ github.repository }}'.split('/')[1];

            const tagsList = github.repos.list

            const { data: deployments } = await github.repos.listDeployments({
              owner,
              repo
            });

            const statuses = (await Promise.all(deployments.map(({ id }) => github.repos.listDeploymentStatuses({
              owner,
              repo,
              deployment_id: id
            })))).map(({ data }) => data);

            console.log('Status', JSON.stringify(statuses));

