name: Update Deployment Status

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  status:
    name: Update Deployment Status
    runs-on: ubuntu-latest
    steps:
      - name: Update all deployments
        uses: actions/github-script@v3
        with:
          script: |
            const owner = '${{ github.repository_owner }}';
            const repo = '${{ github.repository }}'.split('/')[1];

            const tagsList = github.repos.list

            const { data: deployments } = await github.repos.listDeployments({
              owner,
              repo
            });

            const statuses = (await Promise.all(deployments.map(async ({ id }) => [id, await github.repos.listDeploymentStatuses({
              owner,
              repo,
              deployment_id: id
            })]))).map(([id, { data }]) => [id, data]);

            await Promise.all(statuses.map(([id, statuses]) => {
              if (statuses.find((status) => status.state === 'pending') || statuses.length === 0) {
                return github.repos.createDeploymentStatus({
                  owner,
                  repo,
                  deployment_id: id,
                  state: 'success'
                })
              }

              return Promise.resolve();
            }));

