name: Update Deployment Status

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  status:
    name: Update Deployment Status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update all deployments
        uses: actions/github-script@v3
        env:
          CHROME_PUBLIC: ${{ secrets.CHROME_PUBLIC }}
          CHROME_PREVIEW: 'CHROME_PREVIEW'
          FIREFOX_PUBLIC: ${{ secrets.FIREFOX_PUBLIC }}
          CHROME_CLIENT_ID: 'CHROME_CLIENT_ID'
          CHROME_CLIENT_SECRET: 'CHROME_CLIENT_SECRET'
          CHROME_REFRESH_TOKEN: 'CHROME_REFRESH_TOKEN'
        with:
          script: |
            const owner = '${{ github.repository_owner }}';
            const repo = '${{ github.repository }}'.split('/')[1];

            const tagsList = github.repos.list

            const { data: deployments } = await github.repos.listDeployments({
              owner,
              repo
            });

            const statuses = await Promise.all(
              deployments.map(async (deployment) => {
                const { data: status } = await github.repos.listDeploymentStatuses({
                  owner,
                  repo,
                  deployment_id: deployment.id
                });

                return [deployment, status];
              })
            );

            await Promise.all(
              statuses.map(async ([deployment, status]) => {
                const [lastStatus] = status.reverse();

                if (lastStatus.state === 'pending') {
                  const [version] = deployment.ref.split('/').reverse();
                  const environment = deployment.environment.toLowerCase().replace(/ /g,'');

                  const check = require(`${process.env.GITHUB_WORKSPACE}/.github/pipeline/check.js`);

                  github.repos.createDeploymentStatus({
                    owner,
                    repo,
                    deployment_id: deployment.id,
                    state: await check(version, environment, {
                      CHROME_PUBLIC: process.env.CHROME_PUBLIC,
                      FIREFOX_PUBLIC: process.env.FIREFOX_PUBLIC
                    })
                  });
                }
              })
            );
