name: Update Deployment Status

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  status:
    name: Update Deployment Status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ./.github/pipeline

      - run: npm run build
        working-directory: ./.github/pipeline

      - name: Update all deployments
        uses: actions/github-script@v3
        env:
          CHROME_LIVE: ${{ secrets.CHROME_LIVE }}
          CHROME_DEVELOPER: ${{ secrets.CHROME_DEVELOPER }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          FIREFOX_LIVE: ${{ secrets.FIREFOX_LIVE }}
          FIREFOX_DEVELOPER: ${{ secrets.FIREFOX_DEVELOPER }}
          FIREFOX_ISS: ${{ secrets.FIREFOX_ISS }}
          FIREFOX_SECRET: ${{ secrets.FIREFOX_SECRET }}
        with:
          script: |
            const owner = '${{ github.repository_owner }}';
            const repo = '${{ github.repository }}'.split('/')[1];

            const updateDeploymentStatuses = require(`${process.env.GITHUB_WORKSPACE}/.github/pipeline/build/status.js`).default;

            await updateDeploymentStatuses(owner, repo, github, core);
