name: Update Deployment Status

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  status:
    name: Update Deployment Status
    runs-on: ubuntu-latest
    steps:
      - name: Update all deployments
        uses: actions/github-script@v3
        with:
          script: |
            const owner = '${{ github.repository_owner }}';
            const repo = '${{ github.repository }}'.split('/')[1];
            const ref = '${{ github.ref }}';

            const deploymentsPromise = github.repos.listDeployments({
              owner,
              repo,
              ref,
            });

            deploymentsPromise.then(({ data: deployments}) => {
              console.log('Deployment', JSON.stringify(deployments));
            });
