name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Bump major/minor/patch?'
        required: true
        default: 'patch'

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Validate Input
        uses: actions/github-script@v3
        with:
          script: |
            if (!['major', 'minor', 'patch'].includes('${{ github.event.inputs.version }}'))
              core.setFailed('Use one of major/minor/patch');

      - uses: actions/checkout@v2

      - uses: dawidd6/action-git-user-config@v1
        with:
          username: Continuous Delivery (Bot)

      - uses: bahmutov/npm-install@v1

      - run: |
          npm version ${{ github.event.inputs.version }}

