name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Bump major/minor/patch?'
        required: true
        default: 'patch'

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Validate input
        uses: actions/github-script@v3
        with:
          script: |
            const level = '${{ github.event.inputs.version }}';
            if (!['major', 'minor', 'patch', 'premajor', 'preminor', 'prepatch', 'prerelease'].includes(level))
              core.setFailed(`Use one of major/minor/patch. Not ${level}`);

      - uses: actions/checkout@v2

      - uses: dawidd6/action-git-user-config@v1

      - uses: bahmutov/npm-install@v1

      - name: Bump version
        run: |
          VERSION=$(make version bump=${{ github.event.inputs.version }} --silent)
          echo "::set-output name=version::$VERSION"
        id: version

      - name: Update main branch
        run: |
          git push --follow-tags || (echo "::error::Pushing the new version failed. You have probably commited other changes in the meantime" && exit 1)

      - name: Create release
        uses: actions/github-script@v3
        with:
          script: |
            const owner = '${{ github.repository_owner }}';
            const repo = '${{ github.repository }}'.split('/')[1];
            const version = '${{ steps.version.outputs.version }}';
            const isPreview = version.includes('preview');

            github.repos.createRelease({
              owner,
              repo,
              tag_name: version,
              name: `Version Release ${version}`,
              prerelease: isPreview
            });

      - name: Handle erros
        if: always()
        uses: actions/github-script@v3
        with:
          script: |
            if ('${{ job.status }}' === 'failure') {
              const owner = '${{ github.repository_owner }}';
              const repo = '${{ github.repository }}'.split('/')[1];
              const sha = '${{ github.sha }}';
              const run_url = 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}';

              github.repos.createCommitComment({
                owner,
                repo,
                commit_sha: sha,
                body: `Bumping the version failed on this commit\nSee: ${run_url}`
              });

              github.repos.createCommitStatus({
                owner,
                repo,
                sha,
                context: 'Continuous Delivery',
                description: 'Version Bump Failed',
                target_url: run_url,
                state: 'failure',
              });
            }

