name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Bump major/minor/patch?'
        required: true
        default: 'patch'

jobs:
  bump_version:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - name: Validate input
        uses: actions/github-script@v3
        with:
          script: |
            if (!['major', 'minor', 'patch'].includes('${{ github.event.inputs.version }}'))
              core.setFailed('Use one of major/minor/patch');

      - uses: actions/checkout@v2

      - uses: dawidd6/action-git-user-config@v1

      - uses: bahmutov/npm-install@v1

      - name: Bump version
        run: |
          npm version ${{ github.event.inputs.version }} -m "Bump version to v%s"

      - name: Update main branch
        run: |
          git push --follow-tags || (echo "::error::Pushing the version bump failed" && exit 1)

      - name: Handle erros
        if: always()
        uses: actions/github-script@v3
        with:
          script: |
            if ('${{ job.status }}' === 'failure') {
              const owner = '${{ github.repository_owner }}';
              const repo = '${{ github.repository }}'.split('/')[1];
              const sha = '${{ github.sha }}';
              const run_url = 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}';

              github.repos.createCommitComment({
                owner,
                repo,
                commit_sha: sha,
                body: `Bumping the version failed on this commit\nSee: ${run_url}`
              });

              github.repos.createCommitStatus({
                owner,
                repo,
                sha,
                description: 'Version Bump Failed',
                target_url: run_url,
                state: 'failure',
              });
            }

